name: Build, Push & Deploy Frontend to Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ACR_NAME: ${{ secrets.ACR_NAME }}
  KEY_VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
  RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
  CONTAINERAPPS_ENVIRONMENT: ${{ secrets.CONTAINERAPPS_ENVIRONMENT }} # 👈 agregado
  SERVICE_NAME: 'frontend'

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ env.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ env.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ env.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ env.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Get ACR Login Server from Azure Key Vault
        id: get_acr
        run: |
          ACR_LOGIN_SERVER=$(az keyvault secret show --vault-name ${{ env.KEY_VAULT_NAME }} --name acr-login-server --query value -o tsv)
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV

      - name: Docker Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.AZURE_CLIENT_ID }}
          password: ${{ env.AZURE_CLIENT_SECRET }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.SERVICE_NAME }}:${{ github.sha }},${{ env.ACR_LOGIN_SERVER }}/${{ env.SERVICE_NAME }}:latest
          context: .

      - name: Create or Update Container App
        run: |
          if az containerapp show --name frontend --resource-group *** &>/dev/null; then
            echo "Container App frontend exists, updating..."
            az containerapp update \
              --name frontend \
              --resource-group *** \
              --image ***.azurecr.io/frontend:2e3181451e5329b55c361a8021dd4577b42ca89b \
              --set-env-vars AUTH_API_ADDRESS=http://api-gateway:8090/auth,TODOS_API_ADDRESS=http://api-gateway:8090/todos,ZIPKIN_URL=http://zipkin:9411/api/v2/spans
          
            # Ingress se actualiza aparte:
            az containerapp ingress update \
              --name frontend \
              --resource-group *** \
              --type external \
              --target-port 8080
          else
            echo "Container App frontend does not exist, creating..."
            az containerapp create \
              --name frontend \
              --resource-group *** \
              --environment *** \
              --image ***.azurecr.io/frontend:2e3181451e5329b55c361a8021dd4577b42ca89b \
              --registry-server ***.azurecr.io \
              --registry-username *** \
              --registry-password *** \
              --ingress external \
              --target-port 8080 \
              --set-env-vars AUTH_API_ADDRESS=http://api-gateway:8090/auth,TODOS_API_ADDRESS=http://api-gateway:8090/todos,ZIPKIN_URL=http://zipkin:9411/api/v2/spans
          fi

      - name: Azure Logout
        run: az logout
